Receive config
smatsuodev/webserv-old pull request #77
Opened 2024-03-13 12:04 UTC by shmorish

- main関数より、default_pathを渡すのでconfig class の kDeafultPathを削除
- config classのparseConfigFileのreturnをResult型にした

2024-03-13 12:12 UTC, harsssh approved these changes, later dismissed
LGTM

2024-03-14 15:13 UTC, EringiShimeji requested changes

2024-03-14 15:13 UTC, EringiShimeji commented on internal/config/config.hpp
> -    static const std::string kDefaultPath;
DEFAULT_CONFIG_PATHの役割って`Config#kDefaultPath`が担うものだと思ってたんですがどうでしょうか？

2024-03-14 15:14 UTC, EringiShimeji commented
このPR、なぜかスクラムボードに勝手に追加されていました
なんででしょう

2024-03-18 13:24 UTC, EringiShimeji requested changes
コメントしました

2024-03-18 13:24 UTC, EringiShimeji commented on cmd/webserv.cpp
> +    const std::string &path = (argc != 2) ? argv[1] : Config::kDefaultPath;
引数がない時にクラッシュしますね
argc != 2ではなくargc == 2ですかね

2024-03-21 05:15 UTC, smatsuodev commented on cmd/webserv.cpp
> +    const std::string &path = (argc == 2) ? argv[1] : Config::kDefaultPath;
よく考えたら、引数が２つ以上与えられたときの処理として、デフォルトのコンフィグファイルを読むのはおかしいかなと思いました。
argc >= 3だったらエラーメッセージを出すとかはどうでしょうか？

2024-03-23 15:21 UTC, harsssh commented on internal/config/config.hpp
> +    static const std::string kDefaultPath;
超細かいんですけど、メンバとメソッドは書く場所を分けてほしいです。
明確なルールはないんですが、「メンバ + 空行 + メソッド」で並べてることが多いはずです。他のクラス宣言を参考にしてください。

2024-03-29 10:05 UTC, harsssh commented on internal/config/config.cpp
> +const std::string Config::kDefaultPath = "default.conf";
これだとカレントディレクトリがプロジェクトルートの場合、プロジェクトルートにある `default.conf` を読むことになりますが、これでいいんでしたっけ。
(一度に指摘できなくて :pray:)

2024-03-30 11:30 UTC, harsssh submitted a review, later dismissed
LGTM

2024-04-03 02:39 UTC, EringiShimeji reviewed
コメントつけました

2024-04-03 02:39 UTC, EringiShimeji commented on tests/config_parser_test.cpp
> +    //std::string config_string = "route_path / { document_root /var/www/html; }";
このコメントアウトはどう言う意図でしょうか？
もし不要になったテストであれば一旦削除してください。
後から復活させる予定があるのであれば、「// FIXME: 〇〇の実装が終わったら復活させる」とかつけといてください

2024-04-03 02:40 UTC, EringiShimeji reviewed
この変更については一旦大丈夫です

2024-04-05 16:18 UTC, smatsuodev approved these changes

2024-04-06 09:50 UTC, merged