ResponseWriterを実装
smatsuodev/webserv-old pull request #80
Opened 2024-03-15 11:30 UTC by EringiShimeji

タスク: #64

2024-03-23 15:43 UTC, harsssh requested changes
:beer: 飲みながら見たので、的外れだったらごめん

2024-03-23 15:43 UTC, harsssh commented on internal/http/response_writer.hpp
> +        return kProtocolVersion + " " + status_code + " " + status_text + "\n";
HTTP メッセージの区切りは CRLF です。他も同様。
https://datatracker.ietf.org/doc/html/rfc9112#section-2.1

> An HTTP/1.1 message consists of a start-line followed by a CRLF and a sequence of octets in a format similar to the Internet Message Format [[RFC5322](https://datatracker.ietf.org/doc/html/rfc5322)]: zero or more header field lines (collectively referred to as the "headers" or the "header section"), an empty line indicating the end of the header section, and an optional message body.

2024-03-23 15:43 UTC, harsssh commented on internal/http/response_writer.hpp
> +    }
処理内容的に "write" だと誤解を生みそう

2024-03-23 15:43 UTC, harsssh commented on internal/http/response_writer.hpp
> +    }
ここも "write" だと誤解があるかも

2024-03-23 15:43 UTC, harsssh commented on internal/http/response_writer.hpp
> +    }
`setBody` だとそれはそれでまずいですよね。コメントに同意できて、かついい命名が思いつけば変えてください。

2024-03-25 06:07 UTC, EringiShimeji commented on internal/http/response_writer.hpp
> +    }
writeだとクライアントに送っていそうな感じがするということですか？

2024-03-25 07:11 UTC, harsssh commented on internal/http/response_writer.hpp
> +    }
そうです

2024-03-26 09:00 UTC, harsssh approved these changes
LGTM

2024-03-26 09:44 UTC, merged