[WIP] Parse request
smatsuodev/webserv-old pull request #84
Opened 2024-03-17 08:14 UTC by harsssh

2024-03-26 07:52 UTC, EringiShimeji requested changes
まだ見切れてない部分があるんですが、一旦レビュー返します

2024-03-26 07:52 UTC, smatsuodev commented on internal/http/context.cpp
> +    // TODO: set header with ResponseWriter
ここら辺のTODOコメントですが、#80とコンフリクトしそうなので消しておいてください

2024-03-26 07:52 UTC, smatsuodev commented on internal/handler/handler.cpp
> +Result<types::Unit, std::string> Handler::trigger(IContext *ctx) {
Handlerの実装ってこのPRでやる感じでしたっけ？
#80 で実装で良かった気がするのでしょうがどうでしょうか？

2024-03-26 07:52 UTC, smatsuodev commented on internal/http/request.cpp
> +    // TODO: implement
ここのTODOって具体的には何をやる必要がありますか？

2024-03-26 07:52 UTC, smatsuodev commented on internal/http/request.cpp
> +    // TODO: implement
ここのTODOも具体的に書けますか？

2024-03-26 07:52 UTC, smatsuodev commented on internal/http/request_parser.cpp
> +        if (!std::isprint(c) && !(c >= 0x80 && c <= 0xff)) {
ここの0x80と0xffってなんの値でしょうか？

2024-03-26 09:03 UTC, harsssh commented on internal/handler/handler.cpp
> +Result<types::Unit, std::string> Handler::trigger(IContext *ctx) {
curl に応答を返すために仮で書いてたやつですね。戻しておきます。

2024-03-26 09:05 UTC, harsssh commented on internal/handler/handler.cpp
> +Result<types::Unit, std::string> Handler::trigger(IContext *ctx) {
main と意外と差分があって単純に戻せないので、後でいい感じにマージします

2024-03-26 09:09 UTC, harsssh commented on internal/http/request_parser.cpp
> +        if (!std::isprint(c) && !(c >= 0x80 && c <= 0xff)) {
関数の上のコメントに書いてあるとおり文字種として obsolete text が許可されており、その ASCII コードに対応してます。

2024-03-27 12:32 UTC, EringiShimeji requested changes, later dismissed
とりあえずテストコード以外はコメント返しました。
テストコードはまた見れたら見ます...

2024-03-27 12:32 UTC, smatsuodev commented on internal/http/request.cpp
> +    // TODO: クエリパラメータが含まれる場合, リクエストターゲットが absolute-form 以外の場合に返す値を検討する
このTODOですが、戻り値にクエリを含むかどうか検討するという意味でしょうか？

2024-03-27 12:32 UTC, smatsuodev commented on internal/io/reader.hpp
> +    virtual bool eof() const = 0;
isEOFとかの方が良いかなと思ったのですがどうでしょうか？

2024-03-27 12:32 UTC, smatsuodev commented on internal/io/reader.hpp
> +    bool eof_;
isEOFとかの方が良いかなと思ったのですがどうでしょうか？

2024-03-27 12:32 UTC, smatsuodev commented on internal/io/reader.hpp
> +    Ownership ownership_;
fdの扱いを委譲するかどうかを表していると思うのですが、FdReader側でfdをcloseしないといけないケースはどんなケースでしょうか？
また、そこを選べるようにしておくメリットはありますか？

2024-03-27 12:32 UTC, smatsuodev commented on internal/io/reader.hpp
> +    Ownership ownership_;
FdReader::ownership_と同様の質問ですが、どのような意図を想定していますか？

2024-03-27 12:32 UTC, smatsuodev commented on internal/io/reader.cpp
> +        const char *copy_src = buf_ + buf_read_pos_;
この処理があるということは、このメソッドを呼ぶときは毎回同じbufを使う必要があるということであってますか？

2024-03-27 12:32 UTC, EringiShimeji commented on internal/utils/utils.hpp
> +    Option<char *> strnstr(const char *haystack, const char *needle, std::size_t len);
これを定義した理由って、Cの標準ライブラリが使えないからなのかOption型を返したいからなのか、どちらでしょうか？

2024-03-27 12:32 UTC, EringiShimeji commented on internal/io/reader.cpp
> +    // If the delimiter is found, return the line up to the delimiter
[nits] IDEが「'line up'ではなく'line-up'だよ」って指摘してましたね
<img width="495" alt="スクリーンショット 2024-03-27 21 02 06" src="https://github.com/EringiShimeji/webserv/assets/59910028/5f48d3a0-e956-40fc-a47a-4e530917f7dc">

2024-03-27 12:32 UTC, EringiShimeji commented on internal/io/reader.hpp
> +class IReader {
使用するタイミングや用途がわかりやすくするために、このファイルにあるクラスはクラス図・シーケンス図に書けると良いですね。別PBIでも良いですが、いつやれそうですか？

2024-03-27 12:32 UTC, EringiShimeji commented on internal/task/io_task_manager.cpp
> +                continue;
[nits] elseではダメでしょうか？処理的にはどちらも同じかもしれないのですが、コンパクトに書けるのでelseで書けそうであれば修正して欲しいです

2024-03-27 12:32 UTC, EringiShimeji commented on internal/task/io_task_manager.cpp
> +                delete task;
[nits] TODOとして「task->execute()のエラーメッセージの使い道を考える」とか追記しとくと良いかなと思いました。

2024-03-27 12:32 UTC, EringiShimeji commented on internal/task/read_request.cpp
> +        Result<std::pair<std::string, std::string>, std::string> parse_field_result = RequestParser::parseHeaderFieldLine(header);
「<space>\r\n」みたいな行はエラーになるという認識であってますか？

2024-03-27 12:32 UTC, EringiShimeji commented on internal/task/read_request.cpp
> +        char *buf = new char[body_size];
bufがヒープに置かれているのでこのままで問題ないと思ったのですが、TODOではどのようなことを懸念していますか？

2024-03-27 12:32 UTC, EringiShimeji commented on internal/task/read_request.cpp
> +    Option<std::string> maybe_body = None;
[nits] maybeというのはOption型だからそういう命名にしているということですかね？maybeをつけなくても型を見ればOption型であることがわかるので、maybeなくてもいいかなとは思いました。

2024-03-27 12:32 UTC, EringiShimeji commented on internal/utils/utils.cpp
> +std::size_t utils::getStringStreamSize(std::stringstream &ss) {
これテストでしか使ってないのでtests以下に移動しませんか？

2024-03-27 13:08 UTC, harsssh commented on internal/http/request.cpp
> +    // TODO: クエリパラメータが含まれる場合, リクエストターゲットが absolute-form 以外の場合に返す値を検討する
クエリを含む場合についてはその通りです。
また、リクエストターゲットがurlになる場合があるので、その場合url全体(リクエストターゲット自体)を返すのか、パスのみを返すのかを検討しなければならないです。

2024-03-27 13:09 UTC, harsssh commented on internal/io/reader.hpp
> +    virtual bool eof() const = 0;
C++のストリーム関連のライブラリがeofというメソッドを持つので、それ倣っています

2024-03-27 13:22 UTC, harsssh commented on internal/io/reader.hpp
> +    Ownership ownership_;
ライブラリとしてのReaderの使い道を考えると、Readerから読み、さらにfdを直接読むことはあまりないと思います。デストラクタでcloseすれば明示的にリソースを解放する必要もなく楽だと考えました。
また、今回に限ってもFdReaderはソケットのfdの所有権を渡したくない一方、BufferedReaderはnewされたFdReaderの所有権をもらい、デストラクタでdeleteしたいはずです。ここの扱いを統一化するためにも所有権の受け渡しの選択をできるようにしています。

2024-03-27 13:28 UTC, harsssh commented on internal/io/reader.cpp
> +        const char *copy_src = buf_ + buf_read_pos_;
毎回同じbuf、は引数のbufを指していますか？
copy_srcはプライベートなbuf_から計算されるもので、引数で渡されるものとは関係ないです。
(質問の意図と違ったら🙏)

2024-03-27 13:29 UTC, harsssh commented on internal/io/reader.cpp
> +    // If the delimiter is found, return the line up to the delimiter
the line / up to the delimiter の意図で書いてます

2024-03-27 13:30 UTC, harsssh commented on internal/io/reader.hpp
> +class IReader {
Reader周りはクラス図書いてたような？もうちょっと足した方がいいですか？

2024-03-27 13:32 UTC, harsssh commented on internal/task/io_task_manager.cpp
> +                continue;
ここデバッグ時に困ったのでとりあえずで適当に実装足してました。やっときます。

2024-03-27 13:33 UTC, harsssh commented on internal/task/read_request.cpp
> +        Result<std::pair<std::string, std::string>, std::string> parse_field_result = RequestParser::parseHeaderFieldLine(header);
そうです。他にもコロンなし、許可されない文字種などの場合もエラーになります。

2024-03-27 13:34 UTC, harsssh commented on internal/task/read_request.cpp
> +    Option<std::string> maybe_body = None;
使用箇所でbody.unwrap()と書くのが違和感あったので、こういう命名にしてます。

2024-03-27 13:37 UTC, harsssh commented on internal/task/read_request.cpp
> +        char *buf = new char[body_size];
外部からの入力値を元にメモリを確保するので懸念のメモ的に書いたのですが、大丈夫そうなので消しときます。

2024-03-27 13:40 UTC, harsssh commented on internal/utils/utils.hpp
> +    Option<char *> strnstr(const char *haystack, const char *needle, std::size_t len);
std:strnstrがなんかの拡張で、CIでビルドが通らなかったので自前で書いてます

2024-03-27 13:55 UTC, harsssh commented on internal/task/io_task_manager.cpp
> +                continue;
そもそもエラー時に `delete task` するべきなのかも特に考えずにこうしてるので、後々ちゃんと書き換えることを考えたら別に直さなくてもいいと思ったのですがどうですか。(nits 付いてるし)

2024-03-27 13:56 UTC, harsssh commented on internal/task/io_task_manager.cpp
> +                delete task;
TODO は足しときます

2024-03-27 14:00 UTC, harsssh commented on internal/utils/utils.cpp
> +std::size_t utils::getStringStreamSize(std::stringstream &ss) {
テストで使ってるのはこの関数に対するテストですね。
もともと Reader 的なクラスの実装に stringstream を使っていて、欲しくなったユーティリティです。残しておくか、消すかの二択だと思います (消すメリットは特に無いので残しててもいいのでは。残すメリットも無いが。)

2024-03-27 16:04 UTC, harsssh commented
`WriteFile` のコンストラクタのシグネチャが変わったことでコンフリクトが起きてる。

2024-04-03 02:15 UTC, EringiShimeji reviewed
追加でコメントしました。

2024-04-03 02:15 UTC, smatsuodev commented on internal/http/request.cpp
> +    // TODO: クエリパラメータが含まれる場合, リクエストターゲットが absolute-form 以外の場合に返す値を検討する
absolute-form = absolute-URIだと思うのですが、[URIのRFCの4.3](https://datatracker.ietf.org/doc/html/rfc3986#section-4.3)には
`absolute-URI  = scheme ":" hier-part [ "?" query ]`
と定義されてるので、origin-formかabsolute-formかに関わらずクエリのことは考慮する必要があると思いました。

これで認識あってればコメントにこの件を反映できますか？

2024-04-03 02:15 UTC, smatsuodev commented on internal/task/io_task_manager.cpp
> +                continue;
前置きですが、「nits ≠ 直さなくてもいい」ではなくて「些細な点ですがレビューつけました」という意味でつけてました。他のレビュー箇所と一緒で直すかどうかは議論して決めた方が良いと考えてます。

今回のケースの背景を説明すると
「直さなくても99%普通に動くし、好みかもしれないから直さなくてもいいっちゃいいけど、冗長さは感じるから直して欲しいな」
と思ってコメントしました。後々ちゃんと書き換えるかどうかですが、僕は意外と差分を増やしたくない人なので、気まぐれで書き換えなかったりするかもしれません。

こういう箇所は後回しにすると多分みんな忘れます。でも、ここで直しておくことで以下の副作用をみずきさんに引き起こせるかもしれないなと思ってます。

1. 他の人をレビューするときに、nitsなコメントをつける抵抗感が減る
2. コードの綺麗さ/統一感について、自発的に考える機会が増える
3. この修正をしている間に別のミスを見つけられたり、他のコメントについてふと別のアイデアが思いつくかもしれない

一方で、僕がnitsなコメントをつける点でもいい点があって、
1. 他の人にnitsなコメントをつけてもらいやすくなる（少なくとも自分がコメントした箇所は指摘されやすくなる）
2. 一瞬でもよぎった考えを明文化することで、それに対して批評してもらえる（この文章を書いてる意図はまさにそれです）

などなど...

これらは僕の実体験で主観的な感覚ですが、参考までにコメントしておきます。

結論としては、精神衛生的に僕はシンプルなコードを常に保っておきたいので、できればelseにして欲しいなと思う次第です。

2024-04-03 02:15 UTC, smatsuodev commented on internal/io/reader.cpp
> +        const char *copy_src = buf_ + buf_read_pos_;
僕も何が聞きたかったのかわからないんですが、今読んだら理解できました。
普通にnバイトreadして引数のbufにつめるメソッドであってますよね？
もし合ってたら、コメントアウトにこのメソッドの作用について書いておいて欲しいです。

2024-04-03 02:15 UTC, smatsuodev commented on internal/io/reader.hpp
> +class IReader {
書かれてたんですね...把握漏れでした🙇
今見たら良さそうなので大丈夫です！

2024-04-03 02:15 UTC, EringiShimeji commented on internal/utils/utils.cpp
> +std::size_t utils::getStringStreamSize(std::stringstream &ss) {
カバレッジなどに影響するかもしれないので消しときましょう。
テストも消しておいてください

2024-04-03 02:15 UTC, EringiShimeji commented on internal/utils/utils.hpp
> +    Option<char *> strnstr(const char *haystack, const char *needle, std::size_t len);
把握です。そのビルドが思い出せれば、「std::strnstrではビルドエラーが出ることがあるので自前で実装」と書いた上でワークフローのログへのリンクを貼ってもらえると良いかと思います。

2024-04-03 02:15 UTC, EringiShimeji commented on internal/task/write_file.cpp
>  Result<IOTaskResult, std::string> WriteFile::execute() {
cb_->execute()がセグフォする可能性があるともうのでNULLチェックする処理を追加で挟んでもらえますか？
PBIからはそれますが重要度が高いのでこのPR内でやってくれると助かります。

2024-04-03 02:34 UTC, EringiShimeji commented on internal/io/reader.hpp
> +    Ownership ownership_;
経緯はわかりました。
いつかはfdをRAIIでしっかり管理した方が良さそうですね。別PBIにしときます。

2024-04-03 02:35 UTC, harsssh commented on internal/utils/utils.cpp
> +std::size_t utils::getStringStreamSize(std::stringstream &ss) {
カバレッジを上げることを目的にするべきではない気がします

2024-04-03 02:38 UTC, harsssh commented on internal/io/reader.cpp
> +        const char *copy_src = buf_ + buf_read_pos_;
「このメソッド」は `BufferedReader::read` のことであっていますか? それは基底クラスのヘッダーに書いています。違うようなら再度コメント下さい。

https://github.com/EringiShimeji/webserv/blob/d0a20701d70b25d987f4ffc172ceed0fb34ea8f8/internal/io/reader.hpp#L13-L15

2024-04-03 02:41 UTC, EringiShimeji commented on internal/io/reader.cpp
> +        const char *copy_src = buf_ + buf_read_pos_;
あーすいません...失礼しました...ありがとうございます...

2024-04-03 02:50 UTC, EringiShimeji commented on internal/utils/utils.cpp
> +std::size_t utils::getStringStreamSize(std::stringstream &ss) {
軽く理由聞いてもいいですか？

2024-04-03 02:57 UTC, harsssh commented on internal/http/request.cpp
> +    // TODO: クエリパラメータが含まれる場合, リクエストターゲットが absolute-form 以外の場合に返す値を検討する
検討しなければならないのは以下の2つです。

- クエリは `query` メソッドで取れるので、`path` メソッドで返す文字列に含めるべきか
- absolute-form (`http://example.com/path/to/resource`) で返すべきは URI 全体か、それともリソースへのパス (`/path/to/resource`) のみか

コメントは origin-form と間違えて absolute-form と書いてますね。以下のように修正しようと思いますがどうですか? 認識の齟齬、不足があれば指摘ください。
```
// TODO: クエリパラメータが含まれる場合, またはリクエストターゲットが origin-form 以外の場合に返す値を検討する
```

2024-04-03 03:03 UTC, EringiShimeji commented on internal/http/request.cpp
> +    // TODO: クエリパラメータが含まれる場合, リクエストターゲットが absolute-form 以外の場合に返す値を検討する
認識は合致しました！
TODOのコメントの下の行に「refs: <このdiscussionのリンク>」とかを貼っておけると簡潔で良いかなと思います。

2024-04-03 03:06 UTC, harsssh commented on internal/task/io_task_manager.cpp
> +                continue;
把握です。
ただ `continue` にしたのにも意図があって、ぼくは early return を結構好んで使います。主な理由はブロックのネストを減らすためです。
ぼく自身あまり悪いコードではないと考えているのですが、いかがですか。

2024-04-03 03:11 UTC, EringiShimeji commented on internal/task/io_task_manager.cpp
> +                continue;
であれば問題ないと思います！
というかそもそもここまでレビューしなくていい気がしました。結局好みの問題で議論の余地がないですよね

2024-04-03 03:19 UTC, harsssh commented on internal/utils/utils.cpp
> +std::size_t utils::getStringStreamSize(std::stringstream &ss) {
考え直したら必要になったら履歴を遡ればいいだけなので、デッドコードは削除すべきですね。
未使用なの気づかなかったので指摘助かります。

(関係ないけど、テストは書いてるのでカバレッジの増減はないですね)

2024-04-03 03:31 UTC, EringiShimeji commented on internal/utils/utils.cpp
> +std::size_t utils::getStringStreamSize(std::stringstream &ss) {
修正よろしくお願いします🙇
確かにテストあるからカバレッジ変わんないですね

2024-04-03 03:34 UTC, harsssh commented on internal/task/write_file.cpp
>  Result<IOTaskResult, std::string> WriteFile::execute() {
これ `IOTask` 全部に対する話ですか? それとも `WriteFile` 限定ですか?
(テストでコールバックが `NULL` になっていることに対する対応?)

2024-04-03 03:56 UTC, harsssh commented on internal/task/write_file.cpp
>  Result<IOTaskResult, std::string> WriteFile::execute() {
一旦すべての `IOTask` についてやりますね

2024-04-03 04:10 UTC, harsssh commented on internal/utils/utils.hpp
> +    Option<char *> strnstr(const char *haystack, const char *needle, std::size_t len);
これ見直したらビルドが通らないわけではなく、lint で怒られてました。
https://github.com/EringiShimeji/webserv/actions/runs/8401863622/job/23010687992

前後のコミットで試行錯誤はしていて、`cstring` や `string.h` を include しても解消しなかったため、utils に再実装しています。
lint を黙らせる方法を模索してもいいですが、標準ライブラリに入っていないならやはり使うべきでないと思います。

2024-04-03 04:29 UTC, EringiShimeji commented on internal/task/write_file.cpp
>  Result<IOTaskResult, std::string> WriteFile::execute() {
ありがとうございます！

2024-04-03 04:57 UTC, EringiShimeji commented on internal/utils/utils.hpp
> +    Option<char *> strnstr(const char *haystack, const char *needle, std::size_t len);
なるほどです。そもそも環境依存だったんですね

2024-04-03 04:57 UTC, EringiShimeji approved these changes
良いと思います！

2024-04-03 05:36 UTC, harsssh commented
yatta

2024-04-03 05:36 UTC, merged